# Generated by Django 4.1.7 on 2023-05-14 11:34

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanMudarrisTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255, null=True)),
                ('tugash_vaqti', models.DateTimeField(null=True)),
                ('bitirilgan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FanUstozMudarris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255, null=True)),
                ('tugash_vaqti', models.DateTimeField(null=True)),
                ('bitirilgan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FanUstozTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255, null=True)),
                ('tugash_vaqti', models.DateTimeField(null=True)),
                ('bitirilgan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hujra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('adres', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Ustoz'), (3, 'Mudarris')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adres', models.TextField(null=True)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('telefon_raqami', phone_field.models.PhoneField(blank=True, help_text='Telefon raqami', max_length=31)),
                ('telefon_raqami_tasdiqlangan', models.BooleanField(default=False)),
                ('telefon_raqami_otp', models.CharField(max_length=6, null=True)),
                ('jins', models.CharField(max_length=50, null=True)),
                ('parolga_ishora', models.CharField(max_length=50, null=True)),
                ('profil_surati', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('familya', models.CharField(max_length=255)),
                ('adres', models.TextField(null=True)),
                ('jins', models.CharField(max_length=50)),
                ('profil_surati', models.FileField(null=True, upload_to='')),
                ('pasport_surati', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hujra', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.hujra')),
            ],
        ),
        migrations.CreateModel(
            name='Mudarris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('adres', models.TextField(null=True)),
                ('telefon_raqami', phone_field.models.PhoneField(blank=True, help_text='Telefon raqami', max_length=31, null=True)),
                ('telefon_raqami_tasdiqlangan', models.BooleanField(default=False)),
                ('telefon_raqami_otp', models.CharField(max_length=6, null=True)),
                ('jins', models.CharField(max_length=50, null=True)),
                ('parolga_ishora', models.CharField(max_length=50, null=True)),
                ('profil_surati', models.ImageField(null=True, upload_to='')),
                ('pasport_surati', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hujra', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.hujra')),
            ],
        ),
        migrations.CreateModel(
            name='KundalikBahoUstozTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255, null=True)),
                ('sana', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustoztalaba')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='KundalikBahoUstozMudarris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255, null=True)),
                ('sana', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustozmudarris')),
                ('mudarris', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris')),
            ],
        ),
        migrations.CreateModel(
            name='KundalikBahoMudarrisTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255, null=True)),
                ('sana', models.DateTimeField(default=datetime.datetime(2023, 5, 14, 11, 34, 0, 73711))),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanmudarristalaba')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonBahoUstozTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ustozga_baho', models.FloatField(default=0)),
                ('umumiy_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255, null=True)),
                ('sana', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustoztalaba')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonBahoUstozMudarris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ustozga_baho', models.FloatField(default=0)),
                ('umumiy_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255, null=True)),
                ('sana', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustozmudarris')),
                ('mudarris', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris')),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonBahoMudarrisTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ustozga_baho', models.FloatField(default=0)),
                ('umumiy_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255, null=True)),
                ('sana', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanmudarristalaba')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='hujra',
            name='ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='fanustoztalaba',
            name='talaba',
            field=models.ManyToManyField(to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='fanustoztalaba',
            name='ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='fanustozmudarris',
            name='mudarris',
            field=models.ManyToManyField(to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='fanustozmudarris',
            name='ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='fanmudarristalaba',
            name='mudarris',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='fanmudarristalaba',
            name='talaba',
            field=models.ManyToManyField(to='TBS_app.talaba'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password_hint', models.CharField(max_length=50, null=True)),
                ('profile_pic', models.FileField(null=True, upload_to='admin/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
