# Generated by Django 4.1.7 on 2023-03-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='admin/profile_pic/'),
        ),
    ]
