# Generated by Django 4.1.7 on 2023-05-14 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0002_alter_kundalikbahomudarristalaba_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 11, 35, 23, 433045)),
        ),
    ]
