# Generated by Django 4.1.7 on 2023-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0002_alter_admin_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='course_name',
            new_name='ism',
        ),
        migrations.AddField(
            model_name='kurs',
            name='pic',
            field=models.FileField(null=True, upload_to='admin/profile_pic/'),
        ),
    ]
