# Generated by Django 4.1.7 on 2023-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0003_rename_course_name_kurs_ism_kurs_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='admin/'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='pic',
            field=models.FileField(null=True, upload_to='kurs/'),
        ),
    ]
