# Generated by Django 4.1.7 on 2023-06-12 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TBS_app", "0003_alter_kundalikbahomudarristalaba_sana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kundalikbahomudarristalaba",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 12, 4, 7, 24, 510504)
            ),
        ),
    ]
