# Generated by Django 4.1.7 on 2023-03-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0004_alter_admin_profile_pic_alter_kurs_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hujra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=255)),
                ('adres', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonBaho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ustozga_baho', models.FloatField(default=0)),
                ('umuniy_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KundalikBaho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baho', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mudarrib',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=50, null=True)),
                ('password_hint', models.CharField(max_length=50, null=True)),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mudarriskundalikbaho',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='mudarriskundalikbaho',
            name='mudarris',
        ),
        migrations.RemoveField(
            model_name='talabakundalikbaho',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='talabakundalikbaho',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='ustoz_id',
        ),
        migrations.RemoveField(
            model_name='mudarris',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mudarris',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='mudarris',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='mudarris',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='address',
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='ustoz',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ustoz',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ustoz',
            name='password_hint',
        ),
        migrations.RemoveField(
            model_name='ustoz',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='fan',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
        migrations.DeleteModel(
            name='MudarrisKundalikBaho',
        ),
        migrations.DeleteModel(
            name='TalabaKundalikBaho',
        ),
        migrations.AddField(
            model_name='kundalikbaho',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='imtihonbaho',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='fan',
            name='mudarrib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarrib'),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='mudarrib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarrib'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='hujra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='TBS_app.hujra'),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='Mudarrib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarrib'),
        ),
    ]
