# Generated by Django 4.1.7 on 2023-06-12 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TBS_app", "0004_alter_kundalikbahomudarristalaba_sana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kundalikbahomudarristalaba",
            name="sana",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 12, 19, 57, 37, 817267)
            ),
        ),
    ]
