# Generated by Django 4.1.7 on 2023-03-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0005_hujra_imtihonbaho_kundalikbaho_mudarrib_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mudarrib',
            old_name='address',
            new_name='adres',
        ),
        migrations.RenameField(
            model_name='mudarrib',
            old_name='gender',
            new_name='jins',
        ),
        migrations.RenameField(
            model_name='mudarrib',
            old_name='password_hint',
            new_name='parolga_ishora',
        ),
        migrations.RenameField(
            model_name='mudarrib',
            old_name='pic',
            new_name='profil_surati',
        ),
        migrations.RenameField(
            model_name='talaba',
            old_name='first_name',
            new_name='familya',
        ),
        migrations.RenameField(
            model_name='talaba',
            old_name='last_name',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='talaba',
            old_name='gender',
            new_name='jins',
        ),
        migrations.RenameField(
            model_name='talaba',
            old_name='profile_pic',
            new_name='profil_surati',
        ),
        migrations.AddField(
            model_name='mudarris',
            name='pasport_surati',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
