# Generated by Django 4.1.7 on 2023-03-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0006_rename_address_mudarrib_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihonbaho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imtihonbaho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kundalikbaho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kundalikbaho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
