# Generated by Django 4.1.7 on 2023-03-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0007_imtihonbaho_created_at_imtihonbaho_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hujra',
            name='mudarrib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarrib'),
        ),
        migrations.AddField(
            model_name='hujra',
            name='surat',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
