# Generated by Django 4.1.7 on 2023-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0008_hujra_mudarrib_hujra_surat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustoz',
            name='Mudarrib',
        ),
        migrations.AddField(
            model_name='ustoz',
            name='Mudarrib',
            field=models.ManyToManyField(related_name='mudarrib', to='TBS_app.mudarrib'),
        ),
    ]
