# Generated by Django 4.1.7 on 2023-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0009_remove_ustoz_mudarrib_ustoz_mudarrib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustoz',
            name='Mudarrib',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='mudarris',
            name='mudarrib',
        ),
        migrations.AddField(
            model_name='ustoz',
            name='mudarrib',
            field=models.ManyToManyField(related_name='ustoz', to='TBS_app.mudarrib'),
        ),
        migrations.AddField(
            model_name='fan',
            name='talaba',
            field=models.ManyToManyField(related_name='fan', to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='mudarrib',
            field=models.ManyToManyField(related_name='mudarris', to='TBS_app.mudarrib'),
        ),
    ]
