# Generated by Django 4.1.7 on 2023-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0010_remove_ustoz_mudarrib_remove_fan_talaba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='talaba',
            field=models.ManyToManyField(to='TBS_app.talaba'),
        ),
        migrations.AlterField(
            model_name='mudarris',
            name='mudarrib',
            field=models.ManyToManyField(to='TBS_app.mudarrib'),
        ),
        migrations.AlterField(
            model_name='ustoz',
            name='mudarrib',
            field=models.ManyToManyField(to='TBS_app.mudarrib'),
        ),
    ]
