# Generated by Django 4.1.7 on 2023-03-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0011_alter_fan_talaba_alter_mudarris_mudarrib_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanUstozMudarris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FanUstozTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonBahoMudarrisTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ustozga_baho', models.FloatField(default=0)),
                ('umuniy_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonBahoUstozMudarris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ustozga_baho', models.FloatField(default=0)),
                ('umuniy_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImtihonBahoUstozTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ustozga_baho', models.FloatField(default=0)),
                ('umuniy_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KundalikBahoMudarrisTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baho', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KundalikBahoUstozMudarris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baho', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KundalikBahoUstozTalaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baho', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Fan',
            new_name='FanMudarrisTalaba',
        ),
        migrations.RemoveField(
            model_name='kundalikbaho',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='fanmudarristalaba',
            name='mudarrib',
        ),
        migrations.RemoveField(
            model_name='hujra',
            name='mudarrib',
        ),
        migrations.RemoveField(
            model_name='hujra',
            name='surat',
        ),
        migrations.RemoveField(
            model_name='mudarris',
            name='mudarrib',
        ),
        migrations.RemoveField(
            model_name='ustoz',
            name='mudarrib',
        ),
        migrations.AddField(
            model_name='fanmudarristalaba',
            name='mudarris',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='hujra',
            name='ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='adres',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='hujra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.hujra'),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='jins',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='parolga_ishora',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='profil_surati',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='adres',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='jins',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='parolga_ishora',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='profil_surati',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='hujra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.hujra'),
        ),
        migrations.DeleteModel(
            name='ImtihonBaho',
        ),
        migrations.DeleteModel(
            name='KundalikBaho',
        ),
        migrations.DeleteModel(
            name='Mudarrib',
        ),
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='kundalikbahoustozmudarris',
            name='mudarris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='kundalikbahoustozmudarris',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='kundalikbahomudarristalaba',
            name='mudarris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='kundalikbahomudarristalaba',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustoztalaba',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustoztalaba',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustozmudarris',
            name='mudarris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustozmudarris',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='imtihonbahomudarristalaba',
            name='mudarris',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='imtihonbahomudarristalaba',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='fanustoztalaba',
            name='Ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
        migrations.AddField(
            model_name='fanustoztalaba',
            name='talaba',
            field=models.ManyToManyField(to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='fanustozmudarris',
            name='mudarris',
            field=models.ManyToManyField(to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='fanustozmudarris',
            name='ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
    ]
