# Generated by Django 4.1.7 on 2023-03-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0013_alter_ustoz_profil_surati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mudarris',
            name='hujra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS_app.hujra'),
        ),
    ]
