# Generated by Django 4.1.7 on 2023-03-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0014_alter_mudarris_hujra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imtihonbahomudarristalaba',
            name='mudarris',
        ),
        migrations.RemoveField(
            model_name='imtihonbahomudarristalaba',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='imtihonbahoustozmudarris',
            name='mudarris',
        ),
        migrations.RemoveField(
            model_name='imtihonbahoustozmudarris',
            name='ustoz',
        ),
        migrations.RemoveField(
            model_name='imtihonbahoustoztalaba',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='imtihonbahoustoztalaba',
            name='ustoz',
        ),
        migrations.RemoveField(
            model_name='kundalikbahomudarristalaba',
            name='mudarris',
        ),
        migrations.RemoveField(
            model_name='kundalikbahomudarristalaba',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='kundalikbahoustozmudarris',
            name='mudarris',
        ),
        migrations.RemoveField(
            model_name='kundalikbahoustozmudarris',
            name='ustoz',
        ),
        migrations.RemoveField(
            model_name='kundalikbahoustoztalaba',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='kundalikbahoustoztalaba',
            name='ustoz',
        ),
        migrations.AddField(
            model_name='imtihonbahomudarristalaba',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanmudarristalaba'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustozmudarris',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustozmudarris'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustoztalaba',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustoztalaba'),
        ),
        migrations.AddField(
            model_name='kundalikbahomudarristalaba',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanmudarristalaba'),
        ),
        migrations.AddField(
            model_name='kundalikbahoustozmudarris',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustozmudarris'),
        ),
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustoztalaba'),
        ),
        migrations.AlterField(
            model_name='mudarris',
            name='hujra',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.hujra'),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='hujra',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.hujra'),
        ),
    ]
