# Generated by Django 4.1.7 on 2023-03-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0015_remove_imtihonbahomudarristalaba_mudarris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='pasport_surati',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
