# Generated by Django 4.1.7 on 2023-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0016_talaba_pasport_surati'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='adres',
            field=models.TextField(null=True),
        ),
    ]
