# Generated by Django 4.1.7 on 2023-03-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0017_talaba_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanmudarristalaba',
            name='ism',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fanmudarristalaba',
            name='tugash_vaqti',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fanustozmudarris',
            name='ism',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fanustozmudarris',
            name='tugash_vaqti',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fanustoztalaba',
            name='ism',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fanustoztalaba',
            name='tugash_vaqti',
            field=models.DateTimeField(null=True),
        ),
    ]
