# Generated by Django 4.1.7 on 2023-03-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0018_fanmudarristalaba_ism_fanmudarristalaba_tugash_vaqti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanustoztalaba',
            old_name='Ustoz',
            new_name='ustoz',
        ),
    ]
