# Generated by Django 4.1.7 on 2023-03-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0019_rename_ustoz_fanustoztalaba_ustoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanustoztalaba',
            name='talaba',
            field=models.ManyToManyField(related_name='fanlar', to='TBS_app.talaba'),
        ),
    ]
