# Generated by Django 4.1.7 on 2023-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0020_alter_fanustoztalaba_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanmudarristalaba',
            name='talaba',
            field=models.ManyToManyField(related_name='fanlar_mt', to='TBS_app.talaba'),
        ),
        migrations.AlterField(
            model_name='fanustozmudarris',
            name='mudarris',
            field=models.ManyToManyField(related_name='fanlar_um', to='TBS_app.mudarris'),
        ),
    ]
