# Generated by Django 4.1.7 on 2023-04-03 00:09

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0021_alter_fanmudarristalaba_talaba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mudarris',
            name='telefon_raqami',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='telefon_raqami_otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='telefon_raqami_tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='telefon_raqami',
            field=phone_field.models.PhoneField(blank=True, help_text='Telefon raqami', max_length=31),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='telefon_raqami_otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='telefon_raqami_tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
    ]
