# Generated by Django 4.1.7 on 2023-04-03 00:10

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0022_mudarris_telefon_raqami_mudarris_telefon_raqami_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mudarris',
            name='telefon_raqami',
            field=phone_field.models.PhoneField(blank=True, help_text='Telefon raqami', max_length=31, null=True),
        ),
    ]
