# Generated by Django 4.1.7 on 2023-04-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0023_alter_mudarris_telefon_raqami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanmudarristalaba',
            name='talaba',
            field=models.ManyToManyField(to='TBS_app.talaba'),
        ),
        migrations.AlterField(
            model_name='fanustozmudarris',
            name='mudarris',
            field=models.ManyToManyField(to='TBS_app.mudarris'),
        ),
    ]
