# Generated by Django 4.1.7 on 2023-04-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0024_alter_fanmudarristalaba_talaba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanustoztalaba',
            name='talaba',
            field=models.ManyToManyField(to='TBS_app.talaba'),
        ),
    ]
