# Generated by Django 4.1.7 on 2023-05-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0026_remove_kundalikbahoustoztalaba_fan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kundalikbahoustoztalaba',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='kundalikbahoustoztalaba',
            name='ustoz',
        ),
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.fanustoztalaba'),
        ),
    ]
