# Generated by Django 4.1.7 on 2023-05-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0027_remove_kundalikbahoustoztalaba_talaba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
    ]
