# Generated by Django 4.1.7 on 2023-05-02 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0028_kundalikbahoustoztalaba_talaba'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.ustoz'),
        ),
    ]
