# Generated by Django 4.1.7 on 2023-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0029_kundalikbahoustoztalaba_ustoz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kundalikbahoustoztalaba',
            name='talaba',
        ),
        migrations.RemoveField(
            model_name='kundalikbahoustoztalaba',
            name='ustoz',
        ),
        migrations.AddField(
            model_name='imtihonbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='imtihonbahoustozmudarris',
            name='sana',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='imtihonbahoustoztalaba',
            name='sana',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='kundalikbahoustozmudarris',
            name='sana',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='sana',
            field=models.DateTimeField(null=True),
        ),
    ]
