# Generated by Django 4.1.7 on 2023-05-02 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0030_remove_kundalikbahoustoztalaba_talaba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 7, 2, 31, 946612)),
        ),
    ]
