# Generated by Django 4.1.7 on 2023-05-03 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0031_alter_kundalikbahomudarristalaba_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 4, 4, 55, 461620)),
        ),
        migrations.AlterField(
            model_name='kundalikbahoustoztalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 4, 4, 55, 461367), null=True),
        ),
    ]
