# Generated by Django 4.1.7 on 2023-05-03 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0032_alter_kundalikbahomudarristalaba_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 4, 16, 9, 55786)),
        ),
        migrations.AlterField(
            model_name='kundalikbahoustoztalaba',
            name='sana',
            field=models.DateTimeField(null=True),
        ),
    ]
