# Generated by Django 4.1.7 on 2023-05-03 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0033_alter_kundalikbahomudarristalaba_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 5, 38, 49, 424583)),
        ),
        migrations.AlterField(
            model_name='kundalikbahoustoztalaba',
            name='sana',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
