# Generated by Django 4.1.7 on 2023-05-04 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0034_alter_kundalikbahomudarristalaba_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 13, 12, 58, 185354)),
        ),
    ]
