# Generated by Django 4.1.7 on 2023-05-08 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0035_alter_kundalikbahomudarristalaba_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 13, 45, 33, 893378)),
        ),
    ]
