# Generated by Django 4.1.7 on 2023-05-08 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0036_kundalikbahoustoztalaba_talaba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihonbahomudarristalaba',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustozmudarris',
            name='mudarris',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AddField(
            model_name='imtihonbahoustoztalaba',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='kundalikbahomudarristalaba',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.talaba'),
        ),
        migrations.AddField(
            model_name='kundalikbahoustozmudarris',
            name='mudarris',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBS_app.mudarris'),
        ),
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 14, 2, 12, 654416)),
        ),
    ]
