# Generated by Django 4.1.7 on 2023-05-10 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0037_imtihonbahomudarristalaba_talaba_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imtihonbahomudarristalaba',
            old_name='umuniy_baho',
            new_name='umumiy_baho',
        ),
        migrations.RenameField(
            model_name='imtihonbahoustozmudarris',
            old_name='umuniy_baho',
            new_name='umumiy_baho',
        ),
        migrations.RenameField(
            model_name='imtihonbahoustoztalaba',
            old_name='umuniy_baho',
            new_name='umumiy_baho',
        ),
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 9, 2, 54, 132099)),
        ),
    ]
