# Generated by Django 4.1.7 on 2023-05-11 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0038_rename_umuniy_baho_imtihonbahomudarristalaba_umumiy_baho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundalikbahomudarristalaba',
            name='izoh',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kundalikbahoustozmudarris',
            name='izoh',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kundalikbahoustoztalaba',
            name='izoh',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imtihonbahomudarristalaba',
            name='izoh',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imtihonbahoustozmudarris',
            name='izoh',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imtihonbahoustoztalaba',
            name='izoh',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 9, 18, 26, 635828)),
        ),
    ]
