# Generated by Django 4.1.7 on 2023-05-13 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0039_kundalikbahomudarristalaba_izoh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hujra',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mudarris',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talaba',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='tasdiqlangan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 18, 54, 29, 684703)),
        ),
    ]
