# Generated by Django 4.1.7 on 2023-05-14 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBS_app', '0040_hujra_tasdiqlangan_mudarris_tasdiqlangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanmudarristalaba',
            name='bitirilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fanustozmudarris',
            name='bitirilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fanustoztalaba',
            name='bitirilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kundalikbahomudarristalaba',
            name='sana',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 9, 28, 43, 103746)),
        ),
    ]
