from django.urls import path, include
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from . import AdminViews, UstozViews, MudarrisViews, views

urlpatterns = [
    path('', views.loginPage, name="login"),
    path('kirish/', views.doLogin, name="doLogin"),
    path('chiqish/', views.chiqish, name="chiqish"),
    path('admin-foydalanuvchi-nomini-tekshirish/', csrf_exempt(AdminViews.UsernameTekshirish.as_view()), name='foydalanuvchi_nomini_tekshirish'),
    path('admin-emailni-tekshirish/', csrf_exempt(AdminViews.EmailTekshirish.as_view()), name="emailni_tekshirish"),
    # -------------------------
     # Admin Urls
     # Admin
     path('admin_asosiy/', AdminViews.admin_asosiy, name="admin_asosiy"),
     path('admin_profil/', AdminViews.admin_profil, name="admin_profil"),
     path('admin_profil/tahrirlash/', AdminViews.admin_profil_tahrirlash, name="admin_profil_tahrirlash"),
     path('admin_profil/tahrirlash/so\'ratni_o\'chirish/', AdminViews.admin_profil_suratni_uchirish, name="admin_profil_suratni_uchirish"),
    # Ustoz
    path('ustozlar/', AdminViews.ustozlar, name="ustozlar"),
    path('ustozlar/kiritish/', AdminViews.ustoz_kiritish, name="ustoz_kiritish"),
    path('ustozlar/<int:id>/', AdminViews.ustoz_profil, name="ustoz_profil"),
    # path('ustozlar/<int:id>/tasdiqlash/', AdminViews.ustoz_tasdiqlash, name="ustoz_tasdiqlash"),
    path('ustozlar/<int:id>/mudarrislar/', AdminViews.ustoz_profil_mudarrislar, name="ustoz_profil_mudarrislar"),
    path('ustozlar/<int:id>/talabalar/', AdminViews.ustoz_profil_talabalar, name="ustoz_profil_talabalar"),
    path('ustozlar/<int:id>/fanlar/', AdminViews.ustoz_profil_fanlar, name="ustoz_profil_fanlar"),
    path('ustozlar/<int:id>/hujralar/', AdminViews.ustoz_profil_hujralar, name="ustoz_profil_hujralar"),
    path('ustozlar/<int:id>/hujralar/kiritish/', AdminViews.ustoz_profil_hujralar_kiritish, name="ustoz_profil_hujralar_kiritish"),
    path('ustozlar/<int:ustozId>/hujralar/<int:hujraId>/o\'chirish/', AdminViews.ustoz_profil_hujralar_uchirish, name="ustoz_profil_hujralar_uchirish"),
    path('ustozlar/<int:id>/tahrirlash/', AdminViews.ustoz_profil_tahrirlash, name="ustoz_profil_tahrirlash"),
    path('ustozlar/<int:id>/o\'chirish/', AdminViews.ustozni_uchirish, name="ustozni_uchirish"),
    path('ustozlar/<int:id>/tahrirlash/profil_so\'ratni_o\'chirish/', AdminViews.ustoz_profil_suratni_uchirish, name="ustoz_profil_suratni_uchirish"),
    # Hujra
    path('xujralar/', AdminViews.hujralar, name="hujralar"),
    path('xujralar/kiritish/', AdminViews.hujra_kiritish, name="hujra_kiritish"),
    path('xujralar/<int:id>/', AdminViews.hujra_profil, name="hujra_profil"),
    path('xujralar/<int:id>/talabalar/', AdminViews.hujra_profil_talabalar, name="hujra_profil_talabalar"),
    path('xujralar/<int:id>/talabalar/kiritish/', AdminViews.hujra_profil_talabalar_kiritish, name="hujra_profil_talabalar_kiritish"),
    path('xujralar/<int:hujraId>/talabalar/<int:talabaId>/o\'chirish/', AdminViews.hujra_profil_talabalar_uchirish, name="hujra_profil_talabalar_uchirish"),
    path('xujralar/<int:id>/mudarrislar/', AdminViews.hujra_profil_mudarrislar, name="hujra_profil_mudarrislar"),
    path('xujralar/<int:id>/mudarrislar/kiritish/', AdminViews.hujra_profil_mudarrislar_kiritish, name="hujra_profil_mudarrislar_kiritish"),
    path('xujralar/<int:hujraId>/mudarrislar/<int:mudarrisId>/o\'chirish/', AdminViews.hujra_profil_mudarrislar_uchirish, name="hujra_profil_mudarrislar_uchirish"),
    path('xujralar/<int:id>/tahrirlash/', AdminViews.hujra_profil_tahrirlash, name="hujra_profil_tahrirlash"),
    path('xujralar/<int:id>/o\'chirish/', AdminViews.hujra_uchirish, name="hujra_uchirish"),
    #Mudarris
    path('mudarrislar/', AdminViews.mudarrislar, name="mudarrislar"),
    path('mudarrislar/kiritish/', AdminViews.mudarris_kiritish, name="mudarris_kiritish"),
    path('mudarrislar/<int:id>/', AdminViews.mudarris_profil, name="mudarris_profil"),
    path('mudarrislar/<int:id>/o\'z_fanlar/', AdminViews.mudarris_profil_uz_fanlar, name="mudarris_profil_uz_fanlar"),
    path('mudarrislar/<int:id>/fanlar/', AdminViews.mudarris_profil_fanlar, name="mudarris_profil_fanlar"),
    path('mudarrislar/<int:id>/fanlar/kiritish/', AdminViews.mudarris_profil_fanlar_kiritish, name="mudarris_profil_fanlar_kiritish"),
    path('mudarrislar/<int:id>/talabalar/', AdminViews.mudarris_profil_talabalar, name="mudarris_profil_talabalar"),
    path('mudarrislar/<int:id>/tahrirlash/', AdminViews.mudarris_profil_tahrirlash, name="mudarris_profil_tahrirlash"),
    path('mudarrislar/<int:id>/tahrirlash/paspurt/', AdminViews.mudarris_paspurt_tahrirlash, name="mudarris_paspurt_tahrirlash"),
    path('mudarrislar/<int:id>/o\'chirish/', AdminViews.mudarrisni_uchirish, name="mudarrisni_uchirish"),
    path('mudarrislar/<int:id>/tahrirlash/profil_so\'ratni_o\'chirish/', AdminViews.mudarris_profil_suratni_uchirish, name="mudarris_profil_suratni_uchirish"),
    path('mudarrislar/<int:id>/tahrirlash/paspurt_so\'ratni_o\'chirish/', AdminViews.mudarris_pasport_suratni_uchirish, name="mudarris_paspurt_suratni_uchirish"),
    # Talaba
    path('talabalar/', AdminViews.talabalar, name="talabalar"),
    path('talabalar/kiritish/', AdminViews.talaba_kiritish, name="talaba_kiritish"),
    path('talabalar/<int:id>/', AdminViews.talaba_profil, name="talaba_profil"),
    path('talabalar/<int:id>/fanlar/', AdminViews.talaba_profil_fanlar, name="talaba_profil_fanlar"),
    path('talabalar/<int:id>/tahrirlash/', AdminViews.talaba_profil_tahrirlash, name="talaba_profil_tahrirlash"),
    path('talabalar/<int:id>/tahrirlash/paspurt/', AdminViews.talaba_paspurt_tahrirlash, name="talaba_paspurt_tahrirlash"),
    path('talabalar/<int:id>/o\'chirish/', AdminViews.talabani_uchirish, name="talabani_uchirish"),
    path('talabalar/<int:id>/tahrirlash/profil_so\'ratni_o\'chirish/', AdminViews.talaba_profil_suratni_uchirish, name="talaba_profil_suratni_uchirish"),
    path('talabalar/<int:id>/tahrirlash/paspurt_so\'ratni_o\'chirish/', AdminViews.talaba_pasport_suratni_uchirish, name="talaba_pasport_suratni_uchirish"),
    # Fan Ustoz - Talaba
    path('fanlar/ustoz_talaba/', AdminViews.fanlar_ustoz_talaba, name="fanlar_ustoz_talaba"),
    path('fanlar/ustoz_talaba/<int:id>/', AdminViews.fan_ustoz_talaba_profil, name="fan_ustoz_talaba_profil"),
    path('fanlar/ustoz_talaba/<int:id>/tahrirlash/', AdminViews.fan_ustoz_talaba_profil_tahrirlash, name="fan_ustoz_talaba_profil_tahrirlash"),
    path('fanlar/ustoz_talaba/<int:id>/talabalar/', AdminViews.fan_ustoz_talaba_profil_talabalar, name="fan_ustoz_talaba_profil_talabalar"),
    path('fanlar/ustoz_talaba/<int:id>/talabalar/kiritish/', AdminViews.fan_ustoz_talaba_profil_talabalar_kiritish, name="fan_ustoz_talaba_profil_talabalar_kiritish"),
    path('fanlar/ustoz_talaba/<int:fanId>/talabalar/<int:talabaId>/uchirish/', AdminViews.fan_ustoz_talaba_profil_talabalar_uchirish, name="fan_ustoz_talaba_profil_talabalar_uchirish"),
    path('fanlar/ustoz_talaba/kiritish/', AdminViews.fan_ustoz_talaba_kiritish, name='fan_ustoz_talaba_kiritish'),
    path('fanlar/ustoz_talaba/<int:id>/uchirish/', AdminViews.fan_ustoz_talaba_uchirish, name="fan_ustoz_talaba_uchirish"),
    # Fan Ustoz - Mudarris
    path('fanlar/ustoz_mudarris/', AdminViews.fanlar_ustoz_mudarris, name="fanlar_ustoz_mudarris"),
    path('fanlar/ustoz_mudarris/<int:id>/', AdminViews.fan_ustoz_mudarris_profil, name="fan_ustoz_mudarris_profil"),
    path('fanlar/ustoz_mudarris/<int:id>/tahrirlash/', AdminViews.fan_ustoz_mudarris_profil_tahrirlash, name="fan_ustoz_mudarris_profil_tahrirlash"),
    path('fanlar/ustoz_mudarris/<int:id>/mudarrislar/', AdminViews.fan_ustoz_mudarris_profil_mudarrislar, name="fan_ustoz_mudarris_profil_mudarrislar"),
    path('fanlar/ustoz_mudarris/<int:id>/mudarrislar/kiritish/', AdminViews.fan_ustoz_mudarris_profil_mudarrislar_kiritish, name="fan_ustoz_mudarris_profil_mudarrislar_kiritish"),
    path('fanlar/ustoz_mudarris/<int:fanId>/mudarrislar/<int:mudarrisId>/uchirish/', AdminViews.fan_ustoz_mudarris_profil_mudarrislar_uchirish, name="fan_ustoz_mudarris_profil_mudarrislar_uchirish"),
    path('fanlar/ustoz_mudarris/kiritish/', AdminViews.fan_ustoz_mudarris_kiritish, name='fan_ustoz_mudarris_kiritish'),
    path('fanlar/ustoz_mudarris/<int:id>/uchirish/', AdminViews.fan_ustoz_mudarris_uchirish, name="fan_ustoz_mudarris_uchirish"),
    # Fan Mudarris - talaba
    path('fanlar/mudarris_talaba/', AdminViews.fanlar_mudarris_talaba, name="fanlar_mudarris_talaba"),
    path('fanlar/mudarris_talaba/<int:id>/', AdminViews.fan_mudarris_talaba_profil, name="fan_mudarris_talaba_profil"),
    path('fanlar/mudarris_talaba/<int:id>/tahrirlash/', AdminViews.fan_mudarris_talaba_profil_tahrirlash, name="fan_mudarris_talaba_profil_tahrirlash"),
    path('fanlar/mudarris_talaba/<int:id>/talabalar/', AdminViews.fan_mudarris_talaba_profil_talabalar, name="fan_mudarris_talaba_profil_talabalar"),
    path('fanlar/mudarris_talaba/<int:id>/talabalar/kiritish/', AdminViews.fan_mudarris_talaba_profil_talabalar_kiritish, name="fan_mudarris_talaba_profil_talabalar_kiritish"),
    path('fanlar/mudarris_talaba/<int:fanId>/talabalar/<int:talabaId>/uchirish/', AdminViews.fan_mudarris_talaba_profil_talabalar_uchirish, name="fan_mudarris_talaba_profil_talabalar_uchirish"),
    path('fanlar/mudarris_talaba/kiritish/', AdminViews.fan_mudarris_talaba_kiritish, name='fan_mudarris_talaba_kiritish'),
    path('fanlar/mudarris_talaba/<int:id>/uchirish/', AdminViews.fan_mudarris_talaba_uchirish, name="fan_mudarris_talaba_uchirish"),
    # Kundalik baholar Ustoz - Talaba
    path('kundalik_baholar/ustoz_talaba/', AdminViews.kundalik_baholar_ustoz_talaba, name="kundalik_baholar_ustoz_talaba"),
    path('kundalik_baholar/ustoz_talaba/fan/<int:id>/', AdminViews.kundalik_baholar_ustoz_talaba_talaba_tanlash, name="kundalik_baholar_ustoz_talaba_talaba_tanlash"),
    path('kundalik_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/', AdminViews.kundalik_baholar_ustoz_talaba_baholar, name="kundalik_baholar_ustoz_talaba_baholar"),
    path('kundalik_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/api/', AdminViews.kundalik_baholar_ustoz_talaba_baholar_api, name="kundalik_baholar_ustoz_talaba_baholar_api"),
    path('kundalik_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/kiritish/', AdminViews.kundalik_baholar_ustoz_talaba_baholar_kiritish, name="kundalik_baholar_ustoz_talaba_baholar_kiritish"),
    path('kundalik_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/', AdminViews.kundalik_baholar_ustoz_talaba_baholar_tahrirlash, name="kundalik_baholar_ustoz_talaba_baholar_tahrirlash"),
    path('kundalik_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/sana/', AdminViews.kundalik_baholar_ustoz_talaba_baholar_sana_tahrirlash, name="kundalik_baholar_ustoz_talaba_baholar_sana_tahrirlash"),
    path('kundalik_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/uchirish/', AdminViews.kundalik_baholar_ustoz_talaba_baholar_uchirish, name="kundalik_baholar_ustoz_talaba_baholar_uchirish"),
    # Kundalik baholar Ustoz - Mudarris
    path('kundalik_baholar/ustoz_mudarris/', AdminViews.kundalik_baholar_ustoz_mudarris, name="kundalik_baholar_ustoz_mudarris"),
    path('kundalik_baholar/ustoz_mudarris/fan/<int:id>/', AdminViews.kundalik_baholar_ustoz_mudarris_mudarris_tanlash, name="kundalik_baholar_ustoz_mudarris_mudarris_tanlash"),
    path('kundalik_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/', AdminViews.kundalik_baholar_ustoz_mudarris_baholar, name="kundalik_baholar_ustoz_mudarris_baholar"),
    path('kundalik_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/api/', AdminViews.kundalik_baholar_ustoz_mudarris_baholar_api, name="kundalik_baholar_ustoz_mudarris_baholar_api"),
    path('kundalik_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/kiritish/', AdminViews.kundalik_baholar_ustoz_mudarris_baholar_kiritish, name="kundalik_baholar_ustoz_mudarris_baholar_kiritish"),
    path('kundalik_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/tahrirlash/', AdminViews.kundalik_baholar_ustoz_mudarris_baholar_tahrirlash, name="kundalik_baholar_ustoz_mudarris_baholar_tahrirlash"),
    path('kundalik_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/tahrirlash/sana/', AdminViews.kundalik_baholar_ustoz_mudarris_baholar_sana_tahrirlash, name="kundalik_baholar_ustoz_mudarris_baholar_sana_tahrirlash"),
    path('kundalik_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/uchirish/', AdminViews.kundalik_baholar_ustoz_mudarris_baholar_uchirish, name="kundalik_baholar_ustoz_mudarris_baholar_uchirish"),
    # Kundalik baholar Mudarris - Talaba
    path('kundalik_baholar/mudarris_talaba/', AdminViews.kundalik_baholar_mudarris_talaba, name="kundalik_baholar_mudarris_talaba"),
    path('kundalik_baholar/mudarris_talaba/fan/<int:id>/', AdminViews.kundalik_baholar_mudarris_talaba_talaba_tanlash, name="kundalik_baholar_mudarris_talaba_talaba_tanlash"),
    path('kundalik_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/', AdminViews.kundalik_baholar_mudarris_talaba_baholar, name="kundalik_baholar_mudarris_talaba_baholar"),
    path('kundalik_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/api/', AdminViews.kundalik_baholar_mudarris_talaba_baholar_api, name="kundalik_baholar_mudarris_talaba_baholar_api"),
    path('kundalik_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/kiritish/', AdminViews.kundalik_baholar_mudarris_talaba_baholar_kiritish, name="kundalik_baholar_mudarris_talaba_baholar_kiritish"),
    path('kundalik_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/', AdminViews.kundalik_baholar_mudarris_talaba_baholar_tahrirlash, name="kundalik_baholar_mudarris_talaba_baholar_tahrirlash"),
    path('kundalik_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/sana/', AdminViews.kundalik_baholar_mudarris_talaba_baholar_sana_tahrirlash, name="kundalik_baholar_mudarris_talaba_baholar_sana_tahrirlash"),
    path('kundalik_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/uchirish/', AdminViews.kundalik_baholar_mudarris_talaba_baholar_uchirish, name="kundalik_baholar_mudarris_talaba_baholar_uchirish"),
    # Imtihon baholar Ustoz - Talaba
    path('imtihon_baholar/ustoz_talaba/', AdminViews.imtihon_baholar_ustoz_talaba, name="imtihon_baholar_ustoz_talaba"),
    path('imtihon_baholar/ustoz_talaba/fan/<int:id>/', AdminViews.imtihon_baholar_ustoz_talaba_talaba_tanlash, name="imtihon_baholar_ustoz_talaba_talaba_tanlash"),
    path('imtihon_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/', AdminViews.imtihon_baholar_ustoz_talaba_baholar, name="imtihon_baholar_ustoz_talaba_baholar"),
    path('imtihon_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/api/', AdminViews.imtihon_baholar_ustoz_talaba_baholar_api, name="imtihon_baholar_ustoz_talaba_baholar_api"),
    path('imtihon_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/kiritish/', AdminViews.imtihon_baholar_ustoz_talaba_baholar_kiritish, name="imtihon_baholar_ustoz_talaba_baholar_kiritish"),
    path('imtihon_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/sana/', AdminViews.imtihon_baholar_ustoz_talaba_baholar_sana_tahrirlash, name="imtihon_baholar_ustoz_talaba_baholar_sana_tahrirlash"),
    path('imtihon_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/', AdminViews.imtihon_baholar_ustoz_talaba_baholar_tahrirlash, name="imtihon_baholar_ustoz_talaba_baholar_tahrirlash"),
    path('imtihon_baholar/ustoz_talaba/fan/<int:fanId>/talaba/<int:talabaId>/uchirish/', AdminViews.imtihon_baholar_ustoz_talaba_baholar_uchirish, name="imtihon_baholar_ustoz_talaba_baholar_uchirish"),
    # Imtihon baholar Ustoz - Mudarris
    path('imtihon_baholar/ustoz_mudarris/', AdminViews.imtihon_baholar_ustoz_mudarris, name="imtihon_baholar_ustoz_mudarris"),
    path('imtihon_baholar/ustoz_mudarris/fan/<int:id>/', AdminViews.imtihon_baholar_ustoz_mudarris_mudarris_tanlash, name="imtihon_baholar_ustoz_mudarris_mudarris_tanlash"),
    path('imtihon_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/', AdminViews.imtihon_baholar_ustoz_mudarris_baholar, name="imtihon_baholar_ustoz_mudarris_baholar"),
    path('imtihon_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/api/', AdminViews.imtihon_baholar_ustoz_mudarris_baholar_api, name="imtihon_baholar_ustoz_mudarris_baholar_api"),
    path('imtihon_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/kiritish/', AdminViews.imtihon_baholar_ustoz_mudarris_baholar_kiritish, name="imtihon_baholar_ustoz_mudarris_baholar_kiritish"),
    path('imtihon_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/tahrirlash/sana/', AdminViews.imtihon_baholar_ustoz_mudarris_baholar_sana_tahrirlash, name="imtihon_baholar_ustoz_mudarris_baholar_sana_tahrirlash"),
    path('imtihon_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/tahrirlash/', AdminViews.imtihon_baholar_ustoz_mudarris_baholar_tahrirlash, name="imtihon_baholar_ustoz_mudarris_baholar_tahrirlash"),
    path('imtihon_baholar/ustoz_mudarris/fan/<int:fanId>/mudarris/<int:mudarrisId>/uchirish/', AdminViews.imtihon_baholar_ustoz_mudarris_baholar_uchirish, name="imtihon_baholar_ustoz_mudarris_baholar_uchirish"),
    # Imtihon baholar Mudarris - Talaba
    path('imtihon_baholar/mudarris_talaba/', AdminViews.imtihon_baholar_mudarris_talaba, name="imtihon_baholar_mudarris_talaba"),
    path('imtihon_baholar/mudarris_talaba/fan/<int:id>/', AdminViews.imtihon_baholar_mudarris_talaba_talaba_tanlash, name="imtihon_baholar_mudarris_talaba_talaba_tanlash"),
    path('imtihon_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/', AdminViews.imtihon_baholar_mudarris_talaba_baholar, name="imtihon_baholar_mudarris_talaba_baholar"),
    path('imtihon_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/api/', AdminViews.imtihon_baholar_mudarris_talaba_baholar_api, name="imtihon_baholar_mudarris_talaba_baholar_api"),
    path('imtihon_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/kiritish/', AdminViews.imtihon_baholar_mudarris_talaba_baholar_kiritish, name="imtihon_baholar_mudarris_talaba_baholar_kiritish"),
    path('imtihon_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/sana/', AdminViews.imtihon_baholar_mudarris_talaba_baholar_sana_tahrirlash, name="imtihon_baholar_mudarris_talaba_baholar_sana_tahrirlash"),
    path('imtihon_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/', AdminViews.imtihon_baholar_mudarris_talaba_baholar_tahrirlash, name="imtihon_baholar_mudarris_talaba_baholar_tahrirlash"),
    path('imtihon_baholar/mudarris_talaba/fan/<int:fanId>/talaba/<int:talabaId>/uchirish/', AdminViews.imtihon_baholar_mudarris_talaba_baholar_uchirish, name="imtihon_baholar_mudarris_talaba_baholar_uchirish"),
    # -------------------------
    # Ustoz Urls
    path('ustoz_asosiy/', UstozViews.ustoz_asosiy, name="ustoz_asosiy"),
    path('ustoz-foydalanuvchi-nomini-tekshirish/', csrf_exempt(UstozViews.UsernameTekshirish.as_view()), name='ustoz_foydalanuvchi_nomini_tekshirish'),
    path('ustoz-emailni-tekshirish/', csrf_exempt(UstozViews.EmailTekshirish.as_view()), name="ustoz_emailni_tekshirish"),
    path('ustoz_profil/', UstozViews.ustoz_profil, name="ustoz_profil"),
    path('ustoz_profil/tahrirlash/', UstozViews.ustoz_profil_tahrirlash, name="ustoz_profil_tahrirlash"),
    path('ustoz_profil/tahrirlash/suratni_uchirish/', UstozViews.ustoz_profil_suratni_uchirish, name="ustoz_profil_suratni_uchirish"),
    # Xujralar
    path('ustoz_xujralar/', UstozViews.hujralar, name="ustoz_hujralar"),
    path('ustoz_xujralar/<int:id>/', UstozViews.hujra_profil, name="ustoz_hujra_profil"),
    path('ustoz_xujralar/<int:id>/mudarrislar/', UstozViews.hujra_profil_mudarrislar, name="ustoz_hujra_profil_mudarrislar"),
    path('ustoz_xujralar/<int:id>/talabalar/', UstozViews.hujra_profil_talabalar, name="ustoz_hujra_profil_talabalar"),
    # Mudarrislar
    path('ustoz_mudarrislar/', UstozViews.mudarrislar, name="ustoz_mudarrislar"),
    path('ustoz_mudarrislar/<int:id>', UstozViews.mudarris_profil, name="ustoz_mudarris_profil"),
    path('ustoz_mudarrislar/<int:id>/fanlar/', UstozViews.mudarris_profil_uz_fanlar, name="ustoz_mudarris_profil_uz_fanlar"),
    path('ustoz_mudarrislar/<int:id>/o\'z_fanlar/', UstozViews.mudarris_profil_fanlar, name="ustoz_mudarris_profil_fanlar"),
    path('ustoz_mudarrislar/<int:id>/talabalar/', UstozViews.mudarris_profil_talabalar, name="ustoz_mudarris_profil_talabalar"),
    # Talabalar
    path('ustoz_talabalar/', UstozViews.talabalar, name="ustoz_talabalar"),
    path('ustoz_talabalar/<int:id>/', UstozViews.talaba_profil, name="ustoz_talaba_profil"),
    path('ustoz_talabalar/<int:id>/fanlar/', UstozViews.talaba_profil_fanlar, name="ustoz_talaba_profil_fanlar"),
    # Fanlar - Talaba
    path('ustoz_fanlar/talaba/', UstozViews.fanlar_talaba, name='ustoz_fanlar_talaba'),
    path('ustoz_fanlar/talaba/<int:id>/', UstozViews.fan_talaba_profil, name='ustoz_fan_talaba_profil'),
    path('ustoz_fanlar/talaba/<int:id>/talabalar/', UstozViews.fan_talaba_profil_talabalar, name='ustoz_fan_talaba_profil_talabalar'),
    # Fanlar - Mudarris
    path('ustoz_fanlar/mudarris/', UstozViews.fanlar_mudarris, name='ustoz_fanlar_mudarris'),
    path('ustoz_fanlar/mudarris/<int:id>/', UstozViews.fan_mudarris_profil, name='ustoz_fan_mudarris_profil'),
    path('ustoz_fanlar/mudarris/<int:id>/mudarrislar/', UstozViews.fan_mudarris_profil_mudarrislar, name='ustoz_fan_mudarris_profil_mudarrislar'),
    # Baho - Talaba
    path('ustoz_baho/talaba_fan/', UstozViews.baho_talaba, name='ustoz_baho_talaba'),
    path('ustoz_baho/talaba_fan/<int:id>/', UstozViews.baho_talaba_tanlash, name='ustoz_baho_talaba_tanlash'),
    path('ustoz_baho/talaba_fan/<int:fanId>/talaba/<int:talabaId>/', UstozViews.baholar_talaba, name='ustoz_baholar_talaba'),
    path('ustoz_baho/talaba_fan/<int:fanId>/talaba/<int:talabaId>/api/', UstozViews.baholar_talaba_api, name='ustoz_baholar_talaba_api'),
    path('ustoz_baho/ftalaba_an/<int:fanId>/talaba/<int:talabaId>/kiritish/', UstozViews.baholar_talaba_kiritish, name='ustoz_baholar_talaba_kiritish'),
    path('ustoz_baho/talaba_fan/<int:fanId>/talaba/<int:talabaId>/sana/tahrirlash/', UstozViews.baholar_talaba_sana_tahrirlash, name='ustoz_baholar_talaba_sana_tahrirlash'),
    path('ustoz_baho/talaba_fan/<int:fanId>/talaba/<int:talabaId>/tahrirlash/', UstozViews.baholar_talaba_tahrirlash, name='ustoz_baholar_talaba_tahrirlash'),
    path('ustoz_baho/talaba_fan/<int:fanId>/talaba/<int:talabaId>/uchirish/', UstozViews.baholar_talaba_uchirish, name='ustoz_baholar_talaba_uchirish'),
    # Baho - Mudarris
    path('ustoz_baho/mudarris_fan/', UstozViews.baho_mudarris, name='ustoz_baho_mudarris'),
    path('ustoz_baho/mudarris_fan/<int:id>/', UstozViews.baho_mudarris_tanlash, name='ustoz_baho_mudarris_tanlash'),
    path('ustoz_baho/mudarris_fan/<int:fanId>/mudarris/<int:mudarrisId>/', UstozViews.baholar_mudarris, name='ustoz_baholar_mudarris'),
    path('ustoz_baho/mudarris_fan/<int:fanId>/mudarris/<int:mudarrisId>/api/', UstozViews.baholar_mudarris_api, name='ustoz_baholar_mudarris_api'),
    path('ustoz_baho/mudarris_fan/<int:fanId>/mudarris/<int:mudarrisId>/kiritish/', UstozViews.baholar_mudarris_kiritish, name='ustoz_baholar_mudarris_kiritish'),
    path('ustoz_baho/mudarris_fan/<int:fanId>/mudarris/<int:mudarrisId>/sana/tahrirlash/', UstozViews.baholar_mudarris_sana_tahrirlash, name='ustoz_baholar_mudarris_sana_tahrirlash'),
    path('ustoz_baho/mudarris_fan/<int:fanId>/mudarris/<int:mudarrisId>/tahrirlash/', UstozViews.baholar_mudarris_tahrirlash, name='ustoz_baholar_mudarris_tahrirlash'),
    path('ustoz_baho/mudarris_fan/<int:fanId>/mudarris/<int:mudarrisId>/uchirish/', UstozViews.baholar_mudarris_uchirish, name='ustoz_baholar_mudarris_uchirish'),
    # -------------------------
    # Mudarris Urls
    path('mudarris_asosiy/', MudarrisViews.mudarris_asosiy, name="mudarris_asosiy"),
    path('mudarris-foydalanuvchi-nomini-tekshirish/', csrf_exempt(MudarrisViews.UsernameTekshirish.as_view()), name='mudarris_foydalanuvchi_nomini_tekshirish'),
    path('mudarris-emailni-tekshirish/', csrf_exempt(MudarrisViews.EmailTekshirish.as_view()), name="mudarris_emailni_tekshirish"),
    path('mudarris_profil/', MudarrisViews.mudarris_profil, name="mudarris_profil"),
    path('mudarris_profil/tahrirlash/', MudarrisViews.mudarris_profil_tahrirlash, name="mudarris_profil_tahrirlash"),
    path('mudarris_profil/tahrirlash/suratni_uchirish/', MudarrisViews.mudarris_profil_suratni_uchirish, name="mudarris_profil_suratni_uchirish"),

]
